### ISSUE TITLE
Sketch Dashboard Img title and axis label

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/DSCI-532_2024_group08_DriveDeepDive#10]
Hello guys I have pull-requested the sketch img. I add a general title and assign some random values. Just curious whether we should also highlight the axis label in this case (which could make the results a little tight because we already have so many options of graphs)

**Comment by charlesxch** [comment]
I think the current axis label is fine. Our website can be larger than the sketch image. No worries
