### ISSUE TITLE
Finalize the proposal

### ISSUE THREAD

**Issue by charlesxch** [UBC-MDS/DSCI-532_2024_group08_DriveDeepDive#11]
I merged the task 1,2&3 into the main branch. There are some typos and grammar issues, though. We need to go through the proposal again to fix these issues and make some updates, if needed.

**Comment by MDSFusionist** [comment]
@charlesxch Thanks so much for putting everything together, Charles. Let's do a review together tomorrow.

**Comment by charlesxch** [comment]
Done with it. Cheers!
